package com.example.demo.domain;
// Generated 3/09/2020 08:10:48 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado"/*, schema = "public"*/)
public class Empleado implements java.io.Serializable {

	private int idEmpleado;
	private Empresa empresa;
	private String nombre;

	public Empleado() {
	}

	public Empleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Empleado(int idEmpleado, Empresa empresa, String nombre) {
		this.idEmpleado = idEmpleado;
		this.empresa = empresa;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "id_empleado", unique = true, nullable = false)
	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa")
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
