package com.example.demo.domain;
// Generated 3/09/2020 08:10:48 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa"/*, schema = "public"*/)
public class Empresa implements java.io.Serializable {

	private int idEmpresa;
	private String nombre;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Empresa() {
	}

	public Empresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public Empresa(int idEmpresa, String nombre, Set<Empleado> empleados) {
		this.idEmpresa = idEmpresa;
		this.nombre = nombre;
		this.empleados = empleados;
	}

	@Id

	@Column(name = "id_empresa", unique = true, nullable = false)
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
